
- type: entity
  parent: MCStructureCorrodible
  id: MCBarricade
  abstract: true
  components:
  - type: Sprite
    sprite: _RMC14/Structures/Walls/Barricades/barricade.rsi
    drawdepth: WallTops
  - type: Corrodible
    structure: false
  - type: Rotatable
  - type: Appearance
  - type: Fixtures
    fixtures:
      fix1:
        shape:
          !type:PhysShapeAabb
          bounds: "-0.49,-0.49,0.49,-0.38"
        density: 500
        mask:
        - FullTileMask
        layer:
        - TableLayer
        - BarricadeImpassable
  - type: RotationDrawDepth
    southDrawDepth: OverMobs
  - type: Barricade
  - type: Damageable
    damageContainer: Inorganic
    damageModifierSet: CMBarricade
  - type: RMCLungeProtection
  - type: InteractionOutline
  - type: RMCDropshipBlocked
  - type: GenericVisualizer
    visuals:
      enum.BarbedWireVisualLayers.Wire:
        barbWired:
          UnWired: { state: metal_wire, visible: false }
          WiredClosed: { state: metal_wire, visible: true }
      enum.SprayAcidedVisuals.Acided:
        acided:
          True:
            sprite: _RMC14/Effects/xeno_spray_acid.rsi
            state: acid
            visible: true
          False:
            visible: false
  - type: DamageMultiplierFlags
    flags: Breaching
  - type: InvulnerabilityTime
    whitelist:
      components:
      - Xeno
    hitsToInvulnerability: 3
  - type: UserInterface
    interfaces:
      enum.RMCConstructionUpgradeUiKey.Key:
        type: RMCConstructionUpgradeBui
