- type: entity
  parent: RMCSmoke
  id: MCSmoke
  suffix: MC
  components:
  - type: Sprite
    sprite: _RMC14/Effects/smoke.rsi
    state: smoke2
  - type: TimedDespawn
    lifetime: 15
  - type: Appearance
  - type: ActiveEdgeSpreader
  - type: EdgeSpreader
    id: MCSmokeAcid
  - type: EvenSmoke
    spawn: MCSmoke
    range: 3
  - type: DeleteOnExplosion

- type: entity
  id: MCSmokeAcid
  name: acid gas
  suffix: MC, Acid
  categories: [ HideSpawnMenu ]
  components:
  - type: Transform
    anchored: true
  - type: Physics
  - type: Fixtures
    fixtures:
      fix1:
        hard: false
        shape:
          !type:PhysShapeAabb
          bounds: "-0.4,-0.4,0.4,0.4"
        mask:
        - MobMask
        layer:
        - MidImpassable
  - type: Occluder
  - type: Sprite
    sprite: _RMC14/Effects/smoke.rsi
    state: smoke2
    color: "#62821D"
  - type: TimedDespawn
    lifetime: 12
  - type: Appearance
  - type: ActiveEdgeSpreader
  - type: EdgeSpreader
    id: MCSmokeAcid
  - type: EvenSmoke
    spawn: MCSmokeAcid
    range: 3
  - type: DamageOverTime
    affectsDead: false
    affectsInfectedNested: false
    armorPiercingDamage:
      groups:
        Burn: 20
        Airloss: 3
    damage:
      groups:
        Burn: 35
    barricadeDamage:
      groups:
        Burn: 8.5
    whitelist:
      components:
      - Marine
      - Xeno
  - type: DeleteOnExplosion

- type: edgeSpreader
  id: MCSmokeAcid
  updatesPerSecond: 2
