- type: Tag
  id: MCSword

- type: Tag
  id: MCKatana

- type: Tag
  id: MCMachete

- type: Tag
  id: MCBayonet

- type: Tag
  id: MCKnife

- type: Tag
  id: MCSpear

- type: entity
  abstract: true
  id: MCBaseMeleeWeapon
  components:
  - type: MeleeDamageMultiplier
    whitelist:
      components:
      - Xeno
  - type: MeleeWeapon
    angle: 0
  - type: CMArmorPiercing
    amount: 20
