- type: entity
  id: MCFirePreMade
  abstract: true
  components:
  - type: Tag
    tags:
    - MCDamageFire
  - type: Transform
    anchored: true
  - type: Physics
    bodyType: Static
  - type: Fixtures
    fixtures:
      fix1:
        shape: !type:PhysShapeAabb
          bounds: "-0.25,-0.25,0.25,0.40"
        density: 1
        mask:
        - ItemMask
  - type: Sprite
    sprite: _MC/Effects/fire.rsi
    noRot: true
    drawdepth: WallTops
    layers:
    - map: [ "base" ]
      state: oldred_3
  - type: Clickable
  - type: InteractionOutline
  - type: PointLight
    radius: 5
    color: "#bf6d02"
  - type: EffectVisuals
  - type: RMCIgniteOnCollide
    maxStacks: 20
    tileDamage:
      groups:
        Burn: 0.5
  - type: DamageOnCollide
    damageDead: false
    fire: true
    damage:
      groups:
        Burn: 45
  - type: TileFire
    id: MCFire
    extinguishInstantly: false
  - type: Appearance
  - type: GenericVisualizer
    visuals:
      enum.TileFireLayers.Base:
        base:
          One: { state: oldred_1 }
          Two: { state: oldred_2 }
          Three: { state: oldred_3 }
  - type: IgnorePredictionHit
  - type: RMCScorchEffectOnSpawn
    decalTag: burnt
    tileLimit: 3

- type: entity
  parent: MCFirePreMade
  id: MCFire
  name: fire
  categories: [ MCContent ]
  placement:
    mode: SnapgridCenter
  components:
  - type: BlockWeeds
