- type: entity
  parent: MCItem
  id: MCBoxBullets
  name: rifle ammunition box (???)
  description: An unknown ammunition box. It comes with a leather strap allowing to wear it on the back.
  abstract: true
  components:
  - type: Item
    size: Huge
  - type: Sprite
    sprite: _RMC14/Objects/Weapons/Guns/Ammunition/Boxes/modular_boxes.rsi
    layers:
    - state: rifle_box
      color: "#ff0000"
    - state: rifle_box_marking
      color: "#00ff00"
    - state: rifle_ammo_full_rounds_base
      map: [ "enum.BulletBoxLayers.Fill" ]
    - state: rifle_ammo_full_rounds_color
      map: [ "enum.BulletBoxLayers2.Fill" ]
      color: "#0000ff"
  - type: GenericVisualizer
    visuals:
      enum.BulletBoxLayers.Fill:
        enum.BulletBoxLayers.Fill:
          Empty: { state: rifle_ammo_full_rounds_base, visible: false }
          Low: { state: rifle_ammo_low_rounds_base, visible: true }
          Medium: { state: rifle_ammo_medium_rounds_base, visible: true }
          High: { state: rifle_ammo_high_rounds_base, visible: true }
          Full: { state: rifle_ammo_full_rounds_base, visible: true }
        enum.BulletBoxLayers2.Fill:
          Empty: { state: rifle_ammo_full_rounds_color, visible: false }
          Low: { state: rifle_ammo_low_rounds_color, visible: true }
          Medium: { state: rifle_ammo_medium_rounds_color, visible: true }
          High: { state: rifle_ammo_high_rounds_color, visible: true }
          Full: { state: rifle_ammo_full_rounds_color, visible: true }
  - type: Appearance
  - type: RMCUnfoldCardboard
    spawns:
    - id: RMCSheetCardboard1
  - type: InteractedBlacklist
    blacklist:
      components:
      - Xeno
  - type: Clothing
    quickEquip: false
    slots:
    - Back
  - type: DropOnUseInHand
  - type: BulletBox
  - type: Tag
    tags:
    - MCAmmoBox

- type: Tag
  id: MCAmmoBox
