using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._MC.ASRS.Ui;

[GenerateTypedNameReferences]
public sealed partial class MCASRSOrderButton : BoxContainer
{
    public MCASRSOrderButton()
    {
        RobustXamlLoader.Load(this);
    }
}
