- type: entity
  id: MCXenoAcidSpray
  name: acid splatter
  description: It burns! It burns, but not as much!
  components:
  - type: Tag
    tags:
    - MCAcidSpray
    - MCDamageAcid
  - type: Sprite
    sprite: _MC/Effects/xeno_acid.rsi
    drawdepth: Effects
    layers:
    - state: acid2
  - type: Transform
    anchored: True
  - type: Physics
    bodyType: Static
  - type: Fixtures
    fixtures:
      fix1:
        hard: false
        shape: !type:PhysShapeAabb
          bounds: "-0.49,-0.49,0.49,0.49"
        mask:
        - FullTileLayer
        layer:
        - FullTileLayer
  - type: TimedDespawn
    lifetime: 0.6
  - type: DamageOnCollide
    acidic: true
    damage:
      groups:
        Burn: 14
    chainDamage:
      groups:
        Burn: 14
    whitelist:
      components:
      - Marine
      - Xeno
  - type: UncloakOnHit
  - type: ExtinguishFire
  - type: IgnorePredictionHit

- type: Tag
  id: MCAcidSpray
